# models.py
#
# This file defines the "shape" of all data flowing through our environment.
# Think of these as contracts: the agent knows exactly what it will receive
# (Observation) and exactly what shape its response must be (Action).
#
# We use Python @dataclass instead of Pydantic here because that's what the
# OpenEnv base classes expect. Dataclasses are like lightweight Pydantic —
# they define typed fields but validate at definition time, not runtime.

from dataclasses import dataclass, field
from typing import List, Optional

# Import the three base classes from OpenEnv.
# Action, Observation, State are abstract "marker" classes — they don't do
# much on their own, but OpenEnv's server uses them to know what's what.
from openenv.core.env_server import Action, Observation, State


# ---------------------------------------------------------------------------
# The Email dataclass
# ---------------------------------------------------------------------------
# This isn't an OpenEnv type — it's just a helper we use to represent one
# email inside the inbox. We'll embed it inside our Observation.

@dataclass
class Email:
    """A single email in the inbox."""
    id: str                        # unique identifier, e.g. "email_001"
    subject: str                   # email subject line
    sender: str                    # who sent it
    body: str                      # email body text
    timestamp: str                 # when it arrived, e.g. "2024-03-28 09:15"
    # Ground truth labels — used by the grader, NOT shown to the agent
    true_category: str             # "urgent", "normal", or "spam"
    true_priority: int             # 1 (highest) to 5 (lowest)


# ---------------------------------------------------------------------------
# EmailAction — what the agent sends TO the environment each step
# ---------------------------------------------------------------------------
# The agent reads the current email and responds with one of these.
# All three fields together handle all three task difficulties:
#   - Task 1 (easy):   just fill in `category`
#   - Task 2 (medium): fill in `category` + `priority`
#   - Task 3 (hard):   fill in all three fields including `reply`

@dataclass
class EmailAction(Action):
    """
    The action an agent takes when processing an email.

    category: How the agent classifies the email.
              Must be one of: "urgent", "normal", "spam"

    priority: How urgent the agent thinks this email is.
              Integer from 1 (most urgent) to 5 (least urgent).

    reply:    A draft reply written by the agent.
              Only graded in Task 3. Can be empty string for Tasks 1 & 2.
    """
    category: str           # required — agent must always classify
    priority: int = 3       # optional — defaults to middle priority
    reply: str = ""         # optional — only needed for Task 3


# ---------------------------------------------------------------------------
# EmailObservation — what the environment sends BACK to the agent each step
# ---------------------------------------------------------------------------
# After each action, the agent receives this. It tells the agent:
#   - What it just processed (the email it acted on)
#   - What's coming next (the next email, if any)
#   - How well it did (feedback — not the reward number, just text)
#   - Whether the episode is over

@dataclass
class EmailObservation(Observation):
    """
    What the agent sees after each step.

    current_email:     The email the agent just processed (or is about to).
    next_email_subject: A preview of the next email, so the agent can plan.
                       None if this was the last email.
    feedback:          A human-readable string telling the agent how it did.
                       e.g. "Correct category! Priority was off by 2."
    emails_remaining:  How many emails are left in this episode.
    done:              True when the inbox is empty (episode over).
    reward:            The reward for this step (0.0 to 1.0).
                       Inherited from OpenEnv's Observation base class.
    """
    current_email: Optional[Email] = None
    next_email_subject: Optional[str] = None
    feedback: str = ""
    emails_remaining: int = 0
    # `done` and `reward` are inherited from the OpenEnv Observation base class


# ---------------------------------------------------------------------------
# EmailState — metadata about the current episode
# ---------------------------------------------------------------------------
# This is returned by state(). It doesn't contain the task data —
# just bookkeeping info about where we are in the episode.

@dataclass
class EmailState(State):
    """
    Metadata about the current episode.

    episode_id:    A unique ID for this run (auto-generated by OpenEnv base).
    step_count:    How many steps have been taken so far.
    task_id:       Which task is active: "classify", "prioritize", or "reply".
    total_reward:  Cumulative reward so far in this episode.
    inbox_size:    Total number of emails in this episode's inbox.
    """
    task_id: str = "classify"      # which of the 3 tasks is active
    total_reward: float = 0.0      # running score for this episode
    inbox_size: int = 0            # how many emails were in the inbox
    # `episode_id` and `step_count` are inherited from OpenEnv's State base class
